//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace chat_생성
{
    using System;
    using System.Collections.Generic;
    
    public partial class gift
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public gift()
        {
            this.alim = new HashSet<alim>();
            this.gift_received = new HashSet<gift_received>();
        }
    
        public int g_no { get; set; }
        public string g_name { get; set; }
        public string g_explanation { get; set; }
        public Nullable<int> g_like { get; set; }
        public Nullable<System.DateTime> g_date { get; set; }
        public Nullable<decimal> g_price { get; set; }
        public Nullable<byte> g_type { get; set; }
        public Nullable<bool> g_PG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<alim> alim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gift_received> gift_received { get; set; }
    }
}
