//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace 데이터_생성__거래_
{
    using System;
    using System.Collections.Generic;
    
    public partial class chat
    {
        public int c_no { get; set; }
        public System.DateTime c_date { get; set; }
        public int c_go { get; set; }
        public int c_take { get; set; }
        public string c_message { get; set; }
        public Nullable<int> f_no { get; set; }
        public int cg_no { get; set; }
        public bool c_delete { get; set; }
    
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
        public virtual chat_group chat_group { get; set; }
        public virtual file file { get; set; }
    }
}
