//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace 데이터넣기__이모티콘_
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class telltokEntities1 : DbContext
    {
        public telltokEntities1()
            : base("name=telltokEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<add_friend> add_friend { get; set; }
        public virtual DbSet<ads> ads { get; set; }
        public virtual DbSet<alim> alim { get; set; }
        public virtual DbSet<chat> chat { get; set; }
        public virtual DbSet<chat_group> chat_group { get; set; }
        public virtual DbSet<emoticon> emoticon { get; set; }
        public virtual DbSet<emoticon_store> emoticon_store { get; set; }
        public virtual DbSet<file> file { get; set; }
        public virtual DbSet<transfer> transfer { get; set; }
        public virtual DbSet<user> user { get; set; }
    }
}
