//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace 데이터넣기__이모티콘_
{
    using System;
    using System.Collections.Generic;
    
    public partial class transfer
    {
        public int t_no { get; set; }
        public Nullable<int> t_go { get; set; }
        public Nullable<int> t_take { get; set; }
        public Nullable<int> t_price { get; set; }
        public string t_message { get; set; }
    
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
    }
}
