//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace 친구_관계_데이터_생성
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class telltokEntities : DbContext
    {
        public telltokEntities()
            : base("name=telltokEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<add_friend> add_friend { get; set; }
        public virtual DbSet<alim> alim { get; set; }
        public virtual DbSet<chat> chat { get; set; }
        public virtual DbSet<file> file { get; set; }
        public virtual DbSet<gift> gift { get; set; }
        public virtual DbSet<gift_type> gift_type { get; set; }
        public virtual DbSet<purchase> purchase { get; set; }
        public virtual DbSet<user> user { get; set; }
    }
}
