//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace 친구_관계_데이터_생성
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public purchase()
        {
            this.alim = new HashSet<alim>();
        }
    
        public int p_no { get; set; }
        public int p_go { get; set; }
        public int p_take { get; set; }
        public int g_no { get; set; }
        public int p_count { get; set; }
        public System.DateTime p_date { get; set; }
        public bool p_isReceive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<alim> alim { get; set; }
        public virtual gift gift { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
    }
}
