//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class gift
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public gift()
        {
            this.purchase = new HashSet<purchase>();
        }
    
        public int g_no { get; set; }
        public string g_name { get; set; }
        public string g_explanation { get; set; }
        public int g_like { get; set; }
        public System.DateTime g_date { get; set; }
        public byte g_discount { get; set; }
        public int g_price { get; set; }
        public int gt_no { get; set; }
        public bool g_PG { get; set; }
    
        public virtual gift_type gift_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<purchase> purchase { get; set; }
    }
}
